# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='championships',
            new_name='titles',
        ),
    ]
