# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161010_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
